name: Build Android Debug APK

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'

    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Install dependencies
      run: npm ci

    - name: Setup Expo CLI
      run: npm install -g @expo/cli@latest

    - name: Setup EAS CLI
      run: npm install -g eas-cli@latest

    - name: Authenticate with Expo
      run: |
        echo "EXPO_TOKEN=${{ secrets.EXPO_TOKEN }}" >> $GITHUB_ENV
        eas whoami
      env:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
    - name: Create EAS Build Configuration
      run: |
        cat > eas.json << 'EOF'
        {
          "cli": {
            "version": ">= 5.2.0",
            "appVersionSource": "remote"
          },
          "build": {
            "debug": {
              "android": {
                "buildType": "apk",
                "gradleCommand": ":app:assembleDebug"
              }
            },
            "preview": {
              "android": {
                "buildType": "apk"
              }
            },
            "production": {}
          },
          "submit": {
            "production": {}
          }
        }
        EOF
    - name: Initialize Expo project
      run: |
        if [ ! -f "app.json" ] && [ ! -f "app.config.js" ]; then
          cat > app.json << 'EOF'
        {
          "expo": {
            "name": "KickLiteApp",
            "slug": "kickliteapp",
            "version": "1.0.0",
            "orientation": "portrait",
            "icon": "./assets/icon.png",
            "userInterfaceStyle": "light",
            "splash": {
              "image": "./assets/splash.png",
              "resizeMode": "contain",
              "backgroundColor": "#ffffff"
            },
            "assetBundlePatterns": [
              "**/*"
            ],
            "ios": {
              "supportsTablet": true
            },
            "android": {
              "adaptiveIcon": {
                "foregroundImage": "./assets/adaptive-icon.png",
                "backgroundColor": "#ffffff"
              }
            },
            "web": {
              "favicon": "./assets/favicon.png"
            }
          }
        }
        EOF
        fi

    - name: Prebuild project
      run: npx expo prebuild --platform android

    - name: Build debug APK
      run: eas build --platform android --profile debug --local --output ./KickLiteApp-debug.apk
      env:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: KickLiteApp-debug-apk
        path: ./KickLiteApp-debug.apk
        retention-days: 30

    - name: Upload APK to release (if main branch)
      if: github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: debug-${{ github.run_number }}
        name: Debug Build ${{ github.run_number }}
        body: |
          Debug APK build from commit ${{ github.sha }}
          
          **Changes:**
          ${{ github.event.head_commit.message }}
        files: ./KickLiteApp-debug.apk
        prerelease: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
