name: Build Expo APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-expo-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node.js 16
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Upgrade react-native if needed
        run: npm install react-native@0.76.9

      - name: Install Expo CLI and expo-doctor
        run: |
          npm install -g expo-cli
          npm install -g expo-doctor

      - name: Run expo-doctor to validate project
        run: npx expo-doctor

      - name: Build unsigned APK
        env:
          EXPO_NO_SEND_TO_REMOTE: 1
        run: expo build:android -t apk --no-wait
